FROM resin/%%RESIN_MACHINE_NAME%%-node

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY package.json ./

RUN JOBS=MAX npm install --unsafe-perm --production && npm cache clean

COPY . ./

CMD npm start
