FROM resin/%%RESIN_MACHINE_NAME%%-alpine-node:6-slim

RUN mkdir -p '/usr/src/app -t'

WORKDIR /usr/src/app -t

COPY package.json ./

RUN JOBS=MAX npm install --unsafe-perm --production

COPY . ./

CMD npm start
